LU DECOMPOSION

import scipy as np

In [4]:
A = [
    [3, 2, 4],
    [2, 0, 2],
    [4, 2, 3]
]

A = np.array(A)
np.linalg.lu(A)

C:\Users\vkgup\AppData\Local\Temp\ipykernel_14932\3736542472.py:7: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = np.array(A)


(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.75, -0.5 ,  1.  ]]),
 array([[ 4. ,  2. ,  3. ],
        [ 0. , -1. ,  0.5],
        [ 0. ,  0. ,  2. ]]))

In [ ]:
MONTE CARLO

In [5]:
import numpy as np

random_numbers = np.random.rand(10**6)

def f(x):
    return (np.tanh(x**2))**2

random_y = f(random_numbers)

average = np.mean(random_y)
average

0.14662193875555396

In [ ]:
import numpy as np

np.random.seed(0)

x = np.arange(0, 100, 1)
random_numbers = np.random.uniform(0, 1, 100)

def y(x):
    return 0.2*x + 0.3*x**2 - 1 + 0.5*(np.random.uniform(0, 1))

z = y(x)
    

In [ ]:
import matplotlib.pyplot as plt 


plt.scatter(x, z, s=0.81)
plt.show()

In [ ]:
degree = 2
coefficients = np.polyfit(x, z, degree)
print("Coefficients of the fitted polynomial:", coefficients)