LU DECOMPOSION

import scipy as np

In [ ]:
A = [
    [3, 2, 4],
    [2, 0, 2],
    [4, 2, 3]
]

A = np.array(A)
np.linalg.lu(A)

C:\Users\vkgup\AppData\Local\Temp\ipykernel_14932\3736542472.py:7: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = np.array(A)


(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.75, -0.5 ,  1.  ]]),
 array([[ 4. ,  2. ,  3. ],
        [ 0. , -1. ,  0.5],
        [ 0. ,  0. ,  2. ]]))

In [ ]:
MONTE CARLO

In [ ]:
import numpy as np

random_numbers = np.random.rand(10**6)

def f(x):
    return (np.tanh(x**2))**2

random_y = f(random_numbers)

average = np.mean(random_y)
average

0.14662193875555396

In [ ]:
import numpy as np

np.random.seed(0)

x = np.arange(0, 100, 1)
random_numbers = np.random.uniform(0, 1, 100)

def y(x):
    return 0.2*x + 0.3*x**2 - 1 + 0.5*(np.random.uniform(0, 1))

z = y(x)
    

In [ ]:
import matplotlib.pyplot as plt 


plt.scatter(x, z, s=0.81)
plt.show()

In [ ]:
degree = 2
coefficients = np.polyfit(x, z, degree)
print("Coefficients of the fitted polynomial:", coefficients)

In [ ]:
x = 10
id(10)


140706994099272

In [ ]:
import numpy as np
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [ ]:
x = np.array([[1,2],[6,7]])
print(x[1,-1])

7


In [ ]:
x = [100,15,9,5,4,3,1]
print(x[-1:1:-2])

[1, 4, 9]


In [ ]:
int("1110",2)

14

# PYTHON DAY 1

In [ ]:
# print function
# mathematical operations
# input function
# defining variable

In [ ]:
print("hello world")
print("this is an easy language to learn english")
print(3.14)
print("my name is", "vinod", 3.14)


hello world
this is an easy language to learn english
3.14
my name is vinod 3.14


In [ ]:
print("vinod\ngupta")
print("ayushman\nkumar\ngupta")

vinod
gupta
ayushman
kumar
gupta


In [ ]:
print(2+3)
print(2-3)
print(2*3)
print(2**3)
print(2/3)
print((2+3)*5)

5
-1
6
8
0.6666666666666666
25


In [3]:
print("hello")

hello


In [7]:
print(input("what is your name?"))

vinod


In [9]:
input("what is your name?")

'vinod'

In [11]:
x = (2+3)**3
print(x)
print(x+5)

125
130


In [17]:
x = input("what is your name? ")
print(x)
print("hello", x)

vinod
hello vinod
