In [3]:
import scipy as np

In [4]:
A = [
    [3, 2, 4],
    [2, 0, 2],
    [4, 2, 3]
]

A = np.array(A)
np.linalg.lu(A)

C:\Users\vkgup\AppData\Local\Temp\ipykernel_18960\3736542472.py:7: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = np.array(A)


(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [ 0.75, -0.5 ,  1.  ]]),
 array([[ 4. ,  2. ,  3. ],
        [ 0. , -1. ,  0.5],
        [ 0. ,  0. ,  2. ]]))

In [15]:
import numpy as np

random_numbers = np.random.rand(10**6)

def f(x):
    return (np.tanh(x**2))**2

random_y = f(random_numbers)

average = np.mean(random_y)
average

0.14657069083351942

In [26]:
np.random.seed(0)

x = np.arange(0, 100, 1)
random_numbers = np.random.uniform(0, 1, 100)

def y(x, eta):
    return 0.2*x + 0.3*x**2 - 1 + 0.5*eta 

z = f()
    

TypeError: f() missing 1 required positional argument: 'x'

In [24]:
import numpy as np

# Create two NumPy arrays (replace these with your actual arrays)
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays horizontally to create a tuple
result_tuple = np.column_stack((array1, array2))

# Print the result
print("Tuple from two arrays:")
print(result_tuple)

Tuple from two arrays:
[[1 4]
 [2 5]
 [3 6]]
